name: Games on Demand at GenCon
short_name: Games on Demand
markdown: redcarpet
pygments: true
timezone: America/Indiana/Indianapolis


url: http://gamesondemand.github.io
twitter_image_path: /images/games-on-demand-logo.jpg
google_analytics_id: UA-53330216-1

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile