name: Games on Demand at GenCon
markdown: redcarpet
pygments: true
timezone: America/Indiana/Indianapolis

url: http://gamesondemand.github.io
twitter_image_path: /images/games-on-demand-logo.jpg
google_analytics_id: UA-53330216-1