---
- :name: ajit-george
  :times:
  - :day: thursday
    :slot: 2PM
    :max_duration: 4
  - :day: thursday
    :slot: 4PM
    :max_duration: 2
  - :day: friday
    :slot: 12PM
    :max_duration: 2
  - :day: friday
    :slot: 4PM
    :max_duration: 2
  - :day: saturday
    :slot: 2PM
    :max_duration: 4
  - :day: saturday
    :slot: 4PM
    :max_duration: 2
  - :day: sunday
    :slot: 12PM
    :max_duration: 4
  - :day: sunday
    :slot: 2PM
    :max_duration: 2
- :name: amanda-valentine
  :times:
  - :day: thursday
    :slot: 2PM
    :max_duration: 2
  - :day: saturday
    :slot: 10AM
    :max_duration: 2
  - :day: sunday
    :slot: 10AM
    :max_duration: 4
  - :day: sunday
    :slot: 12PM
    :max_duration: 2
- :name: andrew-medeiros
  :times:
  - :day: saturday
    :slot: 10AM
    :max_duration: 2
- :name: angela-delong-andersson
  :times:
  - :day: thursday
    :slot: 10AM
    :max_duration: 4
  - :day: thursday
    :slot: 12PM
    :max_duration: 2
  - :day: thursday
    :slot: 4PM
    :max_duration: 2
  - :day: friday
    :slot: 12PM
    :max_duration: 4
  - :day: friday
    :slot: 2PM
    :max_duration: 2
  - :day: saturday
    :slot: 10AM
    :max_duration: 4
  - :day: saturday
    :slot: 12PM
    :max_duration: 2
  - :day: sunday
    :slot: 10AM
    :max_duration: 4
  - :day: sunday
    :slot: 12PM
    :max_duration: 2
- :name: anna-mckibben
  :times:
  - :day: thursday
    :slot: 12PM
    :max_duration: 4
  - :day: thursday
    :slot: 2PM
    :max_duration: 2
  - :day: friday
    :slot: 2PM
    :max_duration: 4
  - :day: friday
    :slot: 4PM
    :max_duration: 2
  - :day: friday
    :slot: 8PM
    :max_duration: 4
  - :day: friday
    :slot: 10PM
    :max_duration: 2
  - :day: saturday
    :slot: 4PM
    :max_duration: 2
  - :day: sunday
    :slot: 2PM
    :max_duration: 2
- :name: anne-horowitz
  :times:
  - :day: thursday
    :slot: 6PM
    :max_duration: 2
  - :day: friday
    :slot: 10PM
    :max_duration: 2
  - :day: saturday
    :slot: 6PM
    :max_duration: 2
- :name: barbara-ng
  :times:
  - :day: thursday
    :slot: 4PM
    :max_duration: 2
  - :day: sunday
    :slot: 10AM
    :max_duration: 2
- :name: bryan-rennekamp
  :times:
  - :day: friday
    :slot: 2PM
    :max_duration: 4
  - :day: friday
    :slot: 4PM
    :max_duration: 2
  - :day: friday
    :slot: 10PM
    :max_duration: 2
  - :day: saturday
    :slot: 4PM
    :max_duration: 4
  - :day: saturday
    :slot: 6PM
    :max_duration: 2
- :name: carl-klutzke
  :times:
  - :day: thursday
    :slot: 6PM
    :max_duration: 2
  - :day: friday
    :slot: 10AM
    :max_duration: 2
  - :day: friday
    :slot: 2PM
    :max_duration: 2
  - :day: saturday
    :slot: 8PM
    :max_duration: 4
  - :day: saturday
    :slot: 10PM
    :max_duration: 2
- :name: dana-fried
  :times:
  - :day: thursday
    :slot: 10AM
    :max_duration: 2
- :name: eric-mersmann
  :times:
  - :day: friday
    :slot: 10AM
    :max_duration: 2
  - :day: friday
    :slot: 6PM
    :max_duration: 4
  - :day: friday
    :slot: 8PM
    :max_duration: 2
  - :day: saturday
    :slot: 10AM
    :max_duration: 4
  - :day: saturday
    :slot: 12PM
    :max_duration: 2
  - :day: saturday
    :slot: 6PM
    :max_duration: 4
  - :day: saturday
    :slot: 8PM
    :max_duration: 2
- :name: evan-torner
  :times:
  - :day: friday
    :slot: 2PM
    :max_duration: 2
  - :day: saturday
    :slot: 10AM
    :max_duration: 2
  - :day: saturday
    :slot: 8PM
    :max_duration: 2
  - :day: saturday
    :slot: 10PM
    :max_duration: 2
  - :day: sunday
    :slot: 10AM
    :max_duration: 2
  - :day: sunday
    :slot: 2PM
    :max_duration: 2
- :name: james-gabrielsen
  :times:
  - :day: friday
    :slot: 2PM
    :max_duration: 2
- :name: james-mendez-hodes
  :times:
  - :day: saturday
    :slot: 10PM
    :max_duration: 2
- :name: james-stuart
  :times:
  - :day: friday
    :slot: 4PM
    :max_duration: 2
  - :day: friday
    :slot: 6PM
    :max_duration: 2
- :name: jason-morningstar
  :times:
  - :day: thursday
    :slot: 6PM
    :max_duration: 2
  - :day: saturday
    :slot: 6PM
    :max_duration: 2
- :name: jay-treat
  :times:
  - :day: thursday
    :slot: 2PM
    :max_duration: 2
  - :day: thursday
    :slot: 4PM
    :max_duration: 2
- :name: jeff-prather
  :times:
  - :day: friday
    :slot: 10AM
    :max_duration: 4
  - :day: friday
    :slot: 12PM
    :max_duration: 2
- :name: jeremy-friesen
  :times:
  - :day: thursday
    :slot: 10AM
    :max_duration: 4
  - :day: thursday
    :slot: 12PM
    :max_duration: 2
  - :day: friday
    :slot: 10AM
    :max_duration: 2
  - :day: friday
    :slot: 6PM
    :max_duration: 4
  - :day: friday
    :slot: 8PM
    :max_duration: 2
  - :day: saturday
    :slot: 8PM
    :max_duration: 2
  - :day: sunday
    :slot: 10AM
    :max_duration: 2
- :name: jeromy-hastings
  :times:
  - :day: thursday
    :slot: 10AM
    :max_duration: 4
  - :day: thursday
    :slot: 12PM
    :max_duration: 2
- :name: john-stavropoulos
  :times:
  - :day: friday
    :slot: 10AM
    :max_duration: 2
  - :day: friday
    :slot: 12PM
    :max_duration: 2
- :name: karen-twelves
  :times:
  - :day: thursday
    :slot: 10AM
    :max_duration: 2
  - :day: thursday
    :slot: 12PM
    :max_duration: 2
- :name: kat-jones
  :times:
  - :day: friday
    :slot: 6PM
    :max_duration: 2
  - :day: friday
    :slot: 10PM
    :max_duration: 2
  - :day: saturday
    :slot: 2PM
    :max_duration: 2
  - :day: saturday
    :slot: 4PM
    :max_duration: 2
  - :day: saturday
    :slot: 8PM
    :max_duration: 2
  - :day: saturday
    :slot: 10PM
    :max_duration: 2
  - :day: sunday
    :slot: 10AM
    :max_duration: 2
- :name: kira-magrann
  :times:
  - :day: friday
    :slot: 8PM
    :max_duration: 2
  - :day: friday
    :slot: 10PM
    :max_duration: 2
  - :day: saturday
    :slot: 6PM
    :max_duration: 4
  - :day: saturday
    :slot: 8PM
    :max_duration: 2
- :name: kristin-firth
  :times:
  - :day: thursday
    :slot: 10AM
    :max_duration: 2
  - :day: thursday
    :slot: 12PM
    :max_duration: 2
  - :day: saturday
    :slot: 12PM
    :max_duration: 4
  - :day: saturday
    :slot: 2PM
    :max_duration: 2
  - :day: sunday
    :slot: 12PM
    :max_duration: 2
  - :day: sunday
    :slot: 2PM
    :max_duration: 2
- :name: mark-krawec
  :times:
  - :day: thursday
    :slot: 6PM
    :max_duration: 2
- :name: matt-honderich
  :times:
  - :day: thursday
    :slot: 6PM
    :max_duration: 2
  - :day: friday
    :slot: 6PM
    :max_duration: 4
  - :day: friday
    :slot: 8PM
    :max_duration: 2
  - :day: saturday
    :slot: 10PM
    :max_duration: 2
  - :day: sunday
    :slot: 2PM
    :max_duration: 2
- :name: shoe-skogen
  :times:
  - :day: saturday
    :slot: 12PM
    :max_duration: 2
- :name: steve-segedy
  :times:
  - :day: friday
    :slot: 12PM
    :max_duration: 2
  - :day: saturday
    :slot: 2PM
    :max_duration: 2
- :name: stras-acimovic
  :times:
  - :day: saturday
    :slot: 10PM
    :max_duration: 2
- :name: terry-hope-romero
  :times:
  - :day: friday
    :slot: 10AM
    :max_duration: 2
  - :day: friday
    :slot: 12PM
    :max_duration: 2
  - :day: saturday
    :slot: 12PM
    :max_duration: 2
- :name: whitney-strix-beltran
  :times:
  - :day: thursday
    :slot: 2PM
    :max_duration: 4
  - :day: thursday
    :slot: 4PM
    :max_duration: 2
  - :day: friday
    :slot: 12PM
    :max_duration: 2
  - :day: friday
    :slot: 4PM
    :max_duration: 2
  - :day: saturday
    :slot: 2PM
    :max_duration: 4
  - :day: saturday
    :slot: 4PM
    :max_duration: 2
  - :day: sunday
    :slot: 12PM
    :max_duration: 4
  - :day: sunday
    :slot: 2PM
    :max_duration: 2
